### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by macchaka** [kijtra/textdiff#1]
日本語を扱うのに使いやすそうなクラスだと思うのですが、READMEやソースコードにライセンスを明示して頂けないでしょうか。
とあるフレームワークで作っているプログラムで使いたいのですが、そのまま読み込んで使うことができないため、改変が必要なのですが、ライセンスが不明なので改変ができずにいます。

ライセンスが明確になれば、それに合わせて検討したいです。

**Comment by kijtra** [comment]
@macchaka ご指摘ありがとうございます🙇
MITライセンスの旨を追加しました。

**Comment by macchaka** [comment]
ありがとうございました！ありがたく使わせて頂きます！！
